apiVersion: v1
kind: ReplicationController
metadata:
  name:  myvertexapp-rc
spec:
   replicas: 2
   selector: 
     app:  myvertexapp
     version: 2.6.2
   template:                                     
     metadata:
       labels:
          app:  myvertexapp
          version: 2.6.2
     spec:
        containers:
        - name:  myvertexapp-container
          image: vinithttps/mywarimage10march2023
          ports:
          - containerPort: 8080 